DROP VIEW DBO.VIEW_TXTS
GO

CREATE VIEW VIEW_TXTS AS 
SELECT T1.BLBJ, 
    ISNULL(T1.TDAT,'') + ISNULL(T2.TDAT,'') + ISNULL(T3.TDAT,'') + ISNULL(T4.TDAT,'') + ISNULL(T5.TDAT,'') 
	+ ISNULL(T6.TDAT,'') + ISNULL(T7.TDAT,'') + ISNULL(T8.TDAT,'') + ISNULL(T9.TDAT,'') + ISNULL(T10.TDAT,'') 
	+ ISNULL(T11.TDAT,'') + ISNULL(T12.TDAT,'') + ISNULL(T13.TDAT,'') + ISNULL(T14.TDAT,'') + ISNULL(T15.TDAT,'') 
	+ ISNULL(T16.TDAT,'') + ISNULL(T17.TDAT,'') + ISNULL(T18.TDAT,'') + ISNULL(T19.TDAT,'') + ISNULL(T20.TDAT,'') 
	+ ISNULL(T21.TDAT,'') TDAT

FROM TXTS T1 
	LEFT JOIN TXTS T2 ON T1.BLBJ=T2.BLBJ AND T1.TXNO+1=T2.TXNO
	LEFT JOIN TXTS T3 ON T2.BLBJ=T3.BLBJ AND T2.TXNO+1=T3.TXNO	
	LEFT JOIN TXTS T4 ON T3.BLBJ=T4.BLBJ AND T3.TXNO+1=T4.TXNO	
	LEFT JOIN TXTS T5 ON T4.BLBJ=T5.BLBJ AND T4.TXNO+1=T5.TXNO	
	LEFT JOIN TXTS T6 ON T5.BLBJ=T6.BLBJ AND T5.TXNO+1=T6.TXNO	
	LEFT JOIN TXTS T7 ON T6.BLBJ=T7.BLBJ AND T6.TXNO+1=T7.TXNO	
	LEFT JOIN TXTS T8 ON T7.BLBJ=T8.BLBJ AND T7.TXNO+1=T8.TXNO	
	LEFT JOIN TXTS T9 ON T8.BLBJ=T9.BLBJ AND T8.TXNO+1=T9.TXNO	
	LEFT JOIN TXTS T10 ON T9.BLBJ=T10.BLBJ AND T9.TXNO+1=T10.TXNO	
	LEFT JOIN TXTS T11 ON T10.BLBJ=T11.BLBJ AND T10.TXNO+1=T11.TXNO	
	LEFT JOIN TXTS T12 ON T11.BLBJ=T12.BLBJ AND T11.TXNO+1=T12.TXNO
	LEFT JOIN TXTS T13 ON T12.BLBJ=T13.BLBJ AND T12.TXNO+1=T13.TXNO	
	LEFT JOIN TXTS T14 ON T13.BLBJ=T14.BLBJ AND T13.TXNO+1=T14.TXNO	
	LEFT JOIN TXTS T15 ON T14.BLBJ=T15.BLBJ AND T14.TXNO+1=T15.TXNO	
	LEFT JOIN TXTS T16 ON T15.BLBJ=T16.BLBJ AND T15.TXNO+1=T16.TXNO	
	LEFT JOIN TXTS T17 ON T16.BLBJ=T17.BLBJ AND T16.TXNO+1=T17.TXNO	
	LEFT JOIN TXTS T18 ON T17.BLBJ=T18.BLBJ AND T17.TXNO+1=T18.TXNO	
	LEFT JOIN TXTS T19 ON T18.BLBJ=T19.BLBJ AND T18.TXNO+1=T19.TXNO	
	LEFT JOIN TXTS T20 ON T19.BLBJ=T20.BLBJ AND T19.TXNO+1=T20.TXNO	
	LEFT JOIN TXTS T21 ON T20.BLBJ=T21.BLBJ AND T20.TXNO+1=T21.TXNO	
WHERE T1.TXNO=1
GO

DROP VIEW VIEW_ERMODAL
GO

CREATE VIEW VIEW_ERMODAL AS
SELECT Obj_Tbl.Name AS TableName,Obj_Tbl.CODE AS TableCode
, Obj_Col.NAME AS FieldName, Obj_Col.CODE AS FieldCode
, [MPDCOLN].[DTTP] AS DataType
, [MPDCOLN].[PRIM] AS PK, [MPDCOLN].[FORN] AS FK, [MPDCOLN].[MAND] AS M
, ObjFK_Tbl.CODE AS FK_Table, FKColunm.CODE AS FK_Field
, TXT_TBLDesc.TDAT AS TblDescription
, TXT_TblAnno.TDAT AS TblAnnotation
, TXT_ColDesc.TDAT AS ColDescription
, TXT_ColAnno.TDAT AS ColAnnotation
, [MPDTABL].[LABL] AS TblLabel
,[SUBM].[NAME] AS SubModal
,[MPDCOLN].[TABL], [MPDCOLN].[COLN]

FROM ((((((((((((MPDCOLN 
INNER JOIN OBJT AS Obj_Col ON [MPDCOLN].[COLN]=Obj_Col.OBJT) 
INNER JOIN OBJT AS Obj_Tbl ON [MPDCOLN].[TABL]=Obj_Tbl.OBJT) 
LEFT JOIN MPDCREF ON [MPDCOLN].[COLN]=[MPDCREF].[TRGT]) 
LEFT JOIN OBJT AS FKColunm ON [MPDCREF].[SRCE]=FKColunm.OBJT) 
LEFT JOIN MPDCOLN AS MPDCOLN_1 ON FKColunm.OBJT=MPDCOLN_1.COLN) 
LEFT JOIN OBJT AS ObjFK_Tbl ON MPDCOLN_1.TABL=ObjFK_Tbl.OBJT) 
INNER JOIN MODL ON Obj_Tbl.MODL=[MODL].[MODL]) 
LEFT JOIN VIEW_TXTS AS TXT_TBLDesc ON Obj_Tbl.DSCR=TXT_TBLDesc.BLBJ) 
LEFT JOIN VIEW_TXTS AS TXT_TblAnno ON Obj_Tbl.ANNT=TXT_TblAnno.BLBJ) 
LEFT JOIN VIEW_TXTS AS TXT_ColDesc ON Obj_Col.DSCR=TXT_ColDesc.BLBJ) 
LEFT JOIN VIEW_TXTS AS TXT_ColAnno ON Obj_Col.ANNT=TXT_ColAnno.BLBJ) 
INNER JOIN MPDTABL ON [MPDCOLN].[TABL]=[MPDTABL].[TABL]) 
LEFT JOIN (SUBO 
	LEFT JOIN SUBM ON [SUBO].[SUBM]=[SUBM].[SUBM]) ON [MPDCOLN].[TABL]=[SUBO].[OBJT]
--ORDER BY [SUBM].[NAME], Obj_Tbl.CODE, [MPDCOLN].[COLN]
GO

SELECT * FROM VIEW_ERMODAL

GO