SELECT A.FG_FABL_PLAC FAB,A.FG_PROD_CODE PART,A.FG_INV_DATE WOD
,A.FG_MAIN_QTY QTY,NULL SUM_QTY,A.FG_LOT_ID,NULL MPS_DATE
FROM ESCM_FAB_FGOUT A
WHERE A.FG_PROD_CODE='TMB176G-T1NAZ6'
  AND A.FG_INV_DATE 
    BETWEEN TRUNC(SYSDATE,'MM') AND TRUNC(ADD_MONTHS(SYSDATE,1),'MM')-1
ORDER BY A.FG_FABL_PLAC,A.FG_PROD_CODE,A.FG_INV_DATE,A.FG_LOT_ID 