SELECT A.FAB_CD,A.PART_ID,A.MPS_DATE,A.QTY,NULL SUM_QTY
FROM ESCM_OP_EMP_MPS_GROS A
WHERE A.PART_ID='TMB176G-T1NAZ6'
  AND A.MPS_DATE
    BETWEEN TRUNC(SYSDATE,'MM') AND TRUNC(ADD_MONTHS(SYSDATE,1),'MM')-1
ORDER BY A.FAB_CD,A.PART_ID,A.MATCH_CD,A.MPS_DATE