SELECT 'DELETE FROM TBL_ACNT_ACCOUNT;' CMD
UNION
SELECT 'INSERT INTO TBL_ACNT_ACCOUNT (ACT_NO,TYP_NO,ACT_NAME,ACT_CATEGORY_REVERSE,ACT_CATEGORY_CASH)'
	+ ' VALUES(' +'''' + ACT_NO+'''' +',''' +TYP_NO +''',''' + ACT_NAME +''',0,0);' CMD
FROM TBL_ACNT_ACCOUNT