TRUNCATE TABLE TBL_TRANSACTION;
TRUNCATE TABLE TBL_AP_PAY_DT;
TRUNCATE TABLE TBL_AR_RECV_DT;
TRUNCATE TABLE TBL_SHIP_DT;
TRUNCATE TABLE TBL_PO_RECV_DT;
DELETE TBL_AP_PAY;
DELETE TBL_AR_RECV;
DELETE TBL_PO_RECV;
DELETE TBL_SHIP;
DELETE TBL_CUSTOMER;
DELETE TBL_SUPPLIER;
DELETE TBL_PRODUCT;
DELETE TBL_EMPLOYE;

INSERT INTO TBL_EMPLOYE(EPY_NO, EPY_NAME, EPY_IS_CAN_LOGIN
, EPY_DESC, EPY_CREATOR)
VALUES('WYS','ADMINISTRATOR',1,'SYSTEM ADMINISTRATOR','DEFAULT')

INSERT INTO TBL_CUSTOMER
(	CUM_NO,CUM_NAME,CUM_PRESIDENT
	,CUM_CONTANT,CUM_CONT_TITLE
	,CUM_TEL1,CUM_TEL2,CUM_FAX
	,CUM_UNIFORM_NO,CUM_INV_ADDR,CUM_ADDR
	,CUM_ZIP_CODE,CUM_ADVANCE_AMOUNT
	,CUM_DESC,CUM_CREATOR
)
SELECT ID, ISNULL(NAME,ID)
, Manager, Contact, ContJob
, TEL1, Tel2, FAX, 
GovID,InvAddr, Addr
, ZipCode,ISNULL(InitPreMoney,0)
, CONVERT(VARCHAR,Remark) ,'STK2000轉檔'
FROM CUSTOM;

INSERT INTO TBL_SUPPLIER
(	SUP_NO, SUP_NAME
	, SUP_PRESIDENT, SUP_CONTANT, SUP_CONT_TITLE
	, SUP_TEL1, SUP_TEL2, SUP_FAX
	, SUP_UNIFORM_NO, SUP_INV_ADDR, SUP_ADDR
	, SUP_ZIP_CODE, SUP_ADVANCE_AMOUNT, SUP_DESC
	, SUP_CREATOR
)
SELECT ID, NAME
	, Manager, Contact, ContJob
	, TEL1, Tel2, FAX
	, GovID, InvAddr, Addr
	, ZipCode,0, CONVERT(VARCHAR,Remark)
	,'STK2000轉檔'
FROM SUPPLY;

INSERT INTO TBL_PRODUCT
(	PRD_NO, PRD_NAME
, PRD_UNIT, PRD_SALE_PRICE, PRD_SAFE_QTY
, PRD_ONHAND, PRD_CUR_COST, PRD_DESC
, PRD_IS_DUMMY, PRD_DUM_COST_RATE, PRD_EXT_COST_RATIO
, PRD_CREATOR)
SELECT ID, NAME
	, Unit, isnull(price,0), isnull(SafeQty,0)
	, NowQty, NowCost,CONVERT(VARCHAR, Remark)
	,0,0,0
	,'STK2000轉檔'
FROM PRODUCT;

INSERT INTO TBL_EMPLOYE
(	EPY_NO, EPY_NAME
, EPY_TEL1, EPY_TEL2, EPY_ADDR
, EPY_IS_CAN_LOGIN, EPY_DESC
, EPY_CREATOR)
SELECT ID, NAME
, Tel1, Tel2, Addr
, 1,CONVERT(VARCHAR, Remark )
,'STK2000轉檔'
FROM STAFF;

INSERT INTO TBL_SHIP
(	CUM_NO, EPY_NO
, SMT_NO, SMT_INV_NO, SMT_DATE
, SMT_DESTINATION, SMT_TOTAL, SMT_TAX
, SMT_NOT_CLEAN, SMT_COST, SMT_DESC
, SMT_STATUS,SMT_CREATOR)
SELECT M.CUSID,ISNULL(M.SALESID,'WYS')
,	CODE, InvID, Date1
, Destination, Amount, Tax
, NotClean, Cost, Remark
, 1,'STK2000轉檔'
FROM CUSMASTER M 
INNER JOIN TBL_CUSTOMER C ON M.CUSID=C.CUM_NO

INSERT INTO TBL_SHIP_DT
(	SMT_NO, SMD_SEQNO,PRD_NO, SMD_PRD_NAME
, SMD_UNIT_PRICE, SMD_QTY, SMD_COST,INV_NO
)
SELECT D.MASTCODE,D.CODE,D.PRODID,D.PRODNAME
,D.PRICE,D.QTY,D.COST,'DEFAULT'
FROM CUSDETAIL D 
INNER JOIN TBL_SHIP M ON D.MASTCODE=M.SMT_NO
INNER JOIN TBL_PRODUCT P ON D.PRODID=P.PRD_NO

INSERT INTO TBL_PO_RECV
(	SUP_NO, RCV_NO, RCV_DATE
, RCV_INV_NO, RCV_TOTAL, RCV_TAX
, RCV_NOT_CLEAN, RCV_DESC
, RCV_STATUS,RCV_CREATOR)
SELECT M.CUSID,	CODE, Date1
, InvID, Amount, Tax
, NotClean, Remark
, 1,'STK2000轉檔'
FROM SUPMASTER M;
	
INSERT INTO TBL_PO_RECV_DT
(RCV_NO, RCD_SEQNO,PRD_NO, RCD_PRD_NAME
, RCD_QTY, RCD_UNIT_PRICE,INV_NO
)
SELECT D.MASTCODE,D.CODE,D.PRODID,D.PRODNAME
,D.QTY,D.PRICE,'DEFAULT'
FROM SUPDETAIL D
INNER JOIN TBL_PRODUCT P ON D.PRODID=P.PRD_NO;

	
INSERT INTO TBL_AR_RECV
( CUM_NO, ARR_NO, ARR_DATE
, ARR_CASH, ARR_CHECK
, ARR_FROM_ADVANCE, ARR_TO_ADVANCE, ARR_DESC
, ARR_CREATOR)
SELECT R.CUSID,R.CODE,R.DATE1
,	isnull(R.CASH,0),isnull(R.BILL,0)
,	isnull(R.SUBMONEY,0),isnull(R.ADDMONEY,0),R.REMARK
, 'STK2000轉檔'
FROM COLMASTER R INNER JOIN TBL_CUSTOMER C ON (R.CUSID=C.CUM_NO);
	

INSERT INTO TBL_AR_RECV_DT
(	ARR_NO, ARD_SEQNO,SMT_NO, ARD_AMOUNT
, ARD_DISCOUNT
)
SELECT D.MASTCODE,D.CODE,D.DOCCODE,D.ACCOUNT
,	D.DISCOUNT	
FROM COLDETAIL D
INNER JOIN TBL_SHIP S ON D.DOCCODE=S.SMT_NO;
	

INSERT INTO TBL_AP_PAY
(	SUP_NO, PAY_NO, PAY_DATE
, PAY_CASH, PAY_CHECK
, PAY_FROM_ADVANCE, PAY_TO_ADVANCE, PAY_DESC
, PAY_CREATOR)
SELECT M.CUSID,M.CODE,	M.DATE1
,	isnull(M.CASH,0),isnull(M.BILL,0)
,	isnull(M.SUBMONEY,0),isnull(M.ADDMONEY,0),M.REMARK
, 'STK2000轉檔'
FROM PAYMASTER M;
	
INSERT INTO TBL_AP_PAY_DT
(	PAY_NO,PAD_SEQNO, RCV_NO, PAD_AMOUNT
, PAD_DISCOUNT
)
SELECT D.MASTCODE,D.CODE,D.DOCCODE,D.ACCOUNT
,	D.DISCOUNT	
FROM PAYDETAIL D
INNER JOIN TBL_PO_RECV R ON D.DOCCODE=R.RCV_NO;

UPDATE TBL_SHIP SET SMT_DATE=SMT_DATE+815;
UPDATE TBL_PO_RECV SET RCV_DATE=RCV_DATE+815;
UPDATE TBL_AR_RECV SET ARR_DATE=ARR_DATE+815;
UPDATE TBL_AP_PAY SET PAY_DATE=PAY_DATE+815;


INSERT INTO TBL_TRANSACTION
(	INV_NO, PRD_NO, TRN_TYPE
, TRN_SRC_NO, TRN_SRC_SEQNO, TRN_DATETIME
, TRN_QTY, TRN_COST,TRN_ONHAND,TRN_AVG_COST
)
SELECT 'DEFAULT' INV_NO,D.PRD_NO,1 TRN_TYPE
,	D.RCV_NO,D.RCD_SEQNO,M.RCV_DATE
,	D.RCD_QTY,D.RCD_UNIT_PRICE,0,0
FROM TBL_PO_RECV M INNER JOIN TBL_PO_RECV_DT D ON M.RCV_NO=D.RCV_NO
UNION
SELECT 'DEFAULT' INV_NO,D.PRD_NO,2 TRN_TYPE
,	D.SMT_NO,D.SMD_SEQNO,M.SMT_DATE
,	D.SMD_QTY*-1,0	,0,0
FROM TBL_SHIP M INNER JOIN TBL_SHIP_DT D ON M.SMT_NO=D.SMT_NO;

UPDATE TBL_SHIP SET SMT_TOTAL=SMT_TOTAL-SMT_TAX;
UPDATE TBL_PO_RECV SET RCV_TOTAL=RCV_TOTAL-RCV_TAX;
UPDATE TBL_SHIP SET SMT_STATUS=1;
UPDATE TBL_PO_RECV SET RCV_STATUS=1;

UPDATE TBL_SHIP SET SMT_NOT_CLEAN=(S.SMT_TOTAL+S.SMT_TAX)-isnull(R.RECEIVED,0)
FROM TBL_SHIP S 
LEFT JOIN 
	(	SELECT SMT_NO,ISNULL(SUM(ARD_AMOUNT+ARD_DISCOUNT),0) RECEIVED
		FROM TBL_AR_RECV_DT
		GROUP BY SMT_NO
	) R ON S.SMT_NO=R.SMT_NO;

/*
INSERT INTO TBL_HIS_SHIP
(HSMT_NO, CUM_NO, EPY_NO
, HSMT_INV_NO, HSMT_DATE, HSMT_DESTINATION
, HSMT_TOTAL, HSMT_TAX, HSMT_COST
, HSMT_DESC, HSMT_CREATOR)
SELECT SMT_NO, CUM_NO, EPY_NO
,SMT_INV_NO, SMT_DATE, SMT_DESTINATION
, SMT_TOTAL, SMT_TAX, SMT_COST
, SMT_DESC, SMT_CREATOR 
FROM TBL_SHIP;

INSERT INTO TBL_HIS_SHIP_DT
(HSMT_NO, HSMD_SEQNO, PRD_NO
, INV_NO, HSMD_PRD_NAME, HSMD_UNIT_PRICE
, HSMD_QTY, HSMD_COST)

SELECT SMT_NO, SMD_SEQNO, PRD_NO
, INV_NO, SMD_PRD_NAME, SMD_UNIT_PRICE
, SMD_QTY, SMD_COST 
FROM TBL_SHIP_DT;


INSERT INTO TBL_HIS_PO_RECV
(HRCV_NO, SUP_NO, HRCV_DATE
, HRCV_INV_NO, HRCV_TOTAL, HRCV_TAX
, HRCV_DESC, HRCV_CREATOR)
SELECT RCV_NO, SUP_NO, RCV_DATE
, RCV_INV_NO, RCV_TOTAL, RCV_TAX
, RCV_DESC, RCV_CREATOR 
FROM TBL_PO_RECV;

INSERT INTO ERP.ERP.TBL_HIS_PO_RECV_DT
(HRCV_NO, RCD_SEQNO, PRD_NO
, INV_NO, RCD_PRD_NAME, RCD_QTY
, RCD_UNIT_PRICE)
SELECT RCV_NO, RCD_SEQNO, PRD_NO
, INV_NO, RCD_PRD_NAME, RCD_QTY
, RCD_UNIT_PRICE 
FROM TBL_PO_RECV_DT;
*/