SELECT AC.FAB_NAME,AC.PART_ID,AC.DATE1,AC.LOT_ID
      ,MIN(PL.DATE1)
FROM EMPMGR.EMP_TBL_JMPS_T3 AC
    ,EMPMGR.EMP_TBL_JMPS_T5 PL
WHERE AC.FAB_NAME=PL.FAB_NAME
  AND AC.PART_ID=PL.PART_ID
  AND (AC.QTY-AC.LOT_QTY)<PL.QTY
  AND AC.PART_ID='TMB176G-T1NAZ6'  
GROUP BY AC.FAB_NAME,AC.PART_ID,AC.DATE1,AC.LOT_ID