
SELECT  DISTINCT ARR.ARR_NO into tbl_TMP_ARRNO
FROM TBL_AR_RECV ARR 
INNER JOIN TBL_AR_RECV_DT ARD ON ARR.ARR_NO=ARD.ARR_NO
INNER JOIN TBL_SHIP SMT ON ARD.SMT_NO =SMT.SMT_NO
WHERE ARR.ARR_DATE<'1/1/2003'
  AND SMT.SMT_NOT_CLEAN=0
  AND ARR.ARR_NO NOT IN
(
SELECT DISTINCT ARR.ARR_NO
FROM TBL_AR_RECV ARR 
INNER JOIN TBL_AR_RECV_DT ARD ON ARR.ARR_NO=ARD.ARR_NO
INNER JOIN TBL_SHIP SMT ON ARD.SMT_NO =SMT.SMT_NO
WHERE ARR.ARR_DATE<'1/1/2003'
  AND SMT.SMT_NOT_CLEAN<>0
);

SELECT  DISTINCT SMT.SMT_NO into tbl_TMP_SMT_NO
FROM TBL_AR_RECV ARR 
INNER JOIN TBL_AR_RECV_DT ARD ON ARR.ARR_NO=ARD.ARR_NO
INNER JOIN TBL_SHIP SMT ON ARD.SMT_NO =SMT.SMT_NO
WHERE ARR.ARR_DATE<'1/1/2003'
  AND SMT.SMT_NOT_CLEAN=0
  AND ARR.ARR_NO NOT IN
(
SELECT DISTINCT ARR.ARR_NO
FROM TBL_AR_RECV ARR 
INNER JOIN TBL_AR_RECV_DT ARD ON ARR.ARR_NO=ARD.ARR_NO
INNER JOIN TBL_SHIP SMT ON ARD.SMT_NO =SMT.SMT_NO
WHERE ARR.ARR_DATE<'1/1/2003'
  AND SMT.SMT_NOT_CLEAN<>0
);

DELETE TBL_AR_RECV_DT WHERE ARR_NO IN
(SELECT ARR_NO FROM TBL_TMP_ARRNO D);

DELETE TBL_AR_RECV WHERE ARR_NO IN
(SELECT ARR_NO FROM TBL_TMP_ARRNO D);

DELETE TBL_SHIP_DT WHERE SMT_NO IN
(SELECT SMT_NO FROM TBL_TMP_SMT_NO);

DELETE TBL_SHIP WHERE SMT_NO IN
(SELECT SMT_NO FROM TBL_TMP_SMT_NO);

--drop TABLE TBL_TMP_ARRNO;
--drop TABLE TBL_TMP_SMT_NO;
