SELECT SUM(A.JND_AMOUNT) BAL
FROM TBL_ACNT_JOURNAL_DT A;


SELECT JNL_NO,SUM(A.JND_AMOUNT) BAL
FROM TBL_ACNT_JOURNAL_DT A
GROUP BY A.JNL_NO
HAVING SUM(A.JND_AMOUNT)<>0;


SELECT C.ACT_NAME,B.*,A.JNL_DESC
FROM TBL_ACNT_JOURNAL A
INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
WHERE EXISTS
( SELECT 1
	FROM
		( SELECT JNL_NO,SUM(A.JND_AMOUNT) BAL
			FROM TBL_ACNT_JOURNAL_DT A
			GROUP BY A.JNL_NO
			HAVING SUM(A.JND_AMOUNT)<>0
		) D
	WHERE A.JNL_NO=D.JNL_NO
)
ORDER BY B.JNL_NO,B.JND_SEQNO