UPDATE TBL_SHIP SET JNL_NO=NULL WHERE SMT_DATE < '01/01/2015';
UPDATE TBL_AR_RECV SET JNL_NO=NULL WHERE ARR_DATE < '01/01/2015';
UPDATE TBL_AP_PAY SET JNL_NO=NULL WHERE PAY_DATE < '01/01/2015';
UPDATE TBL_PO_RECV SET JNL_NO=NULL WHERE RCV_DATE < '01/01/2015';

DELETE FROM TBL_ACNT_JOURNAL_DT
WHERE EXISTS
(	SELECT * FROM TBL_ACNT_JOURNAL A
	WHERE A.JNL_DATE < '01/01/2015'
		AND TBL_ACNT_JOURNAL_DT.JNL_NO=A.JNL_NO
);
DELETE TBL_ACNT_JOURNAL WHERE JNL_DATE < '01/01/2015';
DELETE TBL_ACNT_INIT;
--UPDATE TBL_SYS_PARAM SET SPR_ACNT_YEAR=2005;