DELETE TBL_AP_PAY_DT;
DELETE TBL_AP_PAY;
DELETE FROM TBL_PO_RECV_DT;
DELETE FROM TBL_PO_RECV;
DELETE FROM TBL_TRANSACTION;
INSERT INTO TBL_PO_RECV
SELECT *
FROM ERP_XT2.erp.TBL_PO_RECV;

INSERT INTO TBL_PO_RECV_DT
SELECT *
FROM ERP_XT2.erp.TBL_PO_RECV_DT;

INSERT INTO TBL_AP_PAY
SELECT * FROM ERP_XT2.ERP.TBL_AP_PAY;

INSERT INTO TBL_AP_PAY_DT
SELECT * FROM ERP_XT2.ERP.TBL_AP_PAY_DT;

INSERT INTO TBL_TRANSACTION
SELECT [PRD_NO], [INV_NO], [TRN_TYPE], [TRN_SRC_NO], [TRN_SRC_SEQNO], [TRN_DATETIME], [TRN_QTY], [TRN_COST], [TRN_ONHAND], [TRN_AVG_COST] FROM [ERP_XT2].[erp].[TBL_TRANSACTION];