UPDATE TBL_SHIP SET JNL_NO=NULL;
UPDATE TBL_AR_RECV SET JNL_NO=NULL;
UPDATE TBL_AP_PAY SET JNL_NO=NULL;
UPDATE TBL_PO_RECV SET JNL_NO=NULL;

TRUNCATE TABLE TBL_ACNT_JOURNAL_DT;
DELETE TBL_ACNT_JOURNAL;
UPDATE TBL_SYS_PARAM SET SPR_ACNT_YEAR=2000;


/*========================================================================================
		收款單傳輸
=======================================================================================*/
/* 收款單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'D'+M.ARR_NO JNL_NO,M.ARR_DATE JNL_DATE
      ,CONVERT(VARCHAR,GETDATE(),111)+' 收款單傳輸 '+'('+M.ARR_NO+'-'+B.CUM_NAME+CONVERT(VARCHAR,M.ARR_DATE,111)+')' JNL_DESC
      ,1 JNL_BILL_TYPE,'WYS' JNL_CREATOR
FROM TBL_AR_RECV M 
INNER JOIN TBL_CUSTOMER B ON M.CUM_NO=B.CUM_NO
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003';

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,1 JND_SEQNO,1111 ACT_NO,M.ARR_CASH,'傳輸-收取現金' JND_DESC
FROM TBL_AR_RECV M
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003';

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,2 JND_SEQNO,1131 ACT_NO,M.ARR_CHECK,'傳輸-收取票據' JND_DESC
FROM TBL_AR_RECV M
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003';

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,3 JND_SEQNO,2261 ACT_NO,M.ARR_FROM_ADVANCE,'傳輸-取用預收' JND_DESC
FROM TBL_AR_RECV M
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003';

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,4 JND_SEQNO,4191 ACT_NO,SUM(D.ARD_DISCOUNT) JND_AMOUNT,'傳輸-折讓總額' JND_DESC
FROM TBL_AR_RECV M 
INNER JOIN TBL_AR_RECV_DT D ON M.ARR_NO=D.ARR_NO
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003'
GROUP BY M.ARR_NO;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,5 JND_SEQNO,2261 ACT_NO,-M.ARR_FROM_ADVANCE,'傳輸-累入預收' JND_DESC
FROM TBL_AR_RECV M
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003';

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,6 JND_SEQNO,1141 ACT_NO
			,-(SUM(D.ARD_DISCOUNT)+SUM(D.ARD_AMOUNT)) JND_AMOUNT,'傳輸-沖銷應收帳款' JND_DESC
FROM TBL_AR_RECV M 
INNER JOIN TBL_AR_RECV_DT D ON M.ARR_NO=D.ARR_NO
WHERE M.ARR_DATE BETWEEN '4/25/2003' AND '4/26/2003'
GROUP BY M.ARR_NO;



SELECT D.TYP_MAJOR_TYPE,D.TYP_NO,D.TYP_NAME,SUBSTRING(C.ACT_NO,1,4) ACT_NO,C.ACT_NAME
			,SUM(B.JND_AMOUNT) AMOUNT
FROM TBL_ACNT_JOURNAL A
	INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
WHERE D.TYP_MAJOR_TYPE IN ('資產','負債','業主權益')
GROUP BY D.TYP_MAJOR_TYPE,D.TYP_NO,D.TYP_NAME,SUBSTRING(C.ACT_NO,1,4),C.ACT_NAME
UNION
SELECT '業主權益','99','保留盈餘(或累積虧損)','0000','盈餘'
			,SUM(B.JND_AMOUNT)  AMOUNT
FROM TBL_ACNT_JOURNAL A
	INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
WHERE D.TYP_MAJOR_TYPE NOT IN ('資產','負債','業主權益')
ORDER BY D.TYP_NO