UPDATE TBL_SHIP SET JNL_NO=NULL;
UPDATE TBL_AR_RECV SET JNL_NO=NULL;
UPDATE TBL_AP_PAY SET JNL_NO=NULL;
UPDATE TBL_PO_RECV SET JNL_NO=NULL;

TRUNCATE TABLE TBL_ACNT_JOURNAL_DT;
TRUNCATE TABLE TBL_ACNT_INIT;
DELETE TBL_ACNT_JOURNAL;
UPDATE TBL_SYS_PARAM SET SPR_ACNT_YEAR=1998;
/*========================================================================================
		銷貨單傳輸
=======================================================================================*/
/* 銷貨單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'A'+SMT_NO,SMT_DATE,CONVERT(VARCHAR,GETDATE(),111)+' 銷貨單傳輸 '+SMT_NO+'('+B.CUM_NAME+')' JNL_DESC,1 JNL_BILL_TYPE,'WYS' JNL_CREATOR
FROM TBL_SHIP A
    ,TBL_CUSTOMER B
WHERE A.CUM_NO=B.CUM_NO;

/*傳票明細*/
/*1141=應收帳款*/
INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'A'+SMT_NO,1 JND_SEQNO,1141 ACT_NO,SMT_TOTAL+SMT_TAX ACT_AMOUNT
	,'傳輸-應收帳款' JND_DESC
FROM TBL_SHIP A
    ,TBL_CUSTOMER B
WHERE A.CUM_NO=B.CUM_NO;

/*4111=銷貨收入*/
INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'A'+SMT_NO,2 JND_SEQNO,4111 ACT_NO,-SMT_TOTAL ACT_AMOUNT
	,'傳輸-銷貨收入' JND_DESC
FROM TBL_SHIP A
    ,TBL_CUSTOMER B
WHERE A.CUM_NO=B.CUM_NO;


/*2281=銷項稅額*/
INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'A'+SMT_NO,3 JND_SEQNO,2281 ACT_NO,-SMT_TAX ACT_AMOUNT
	,'傳輸-銷項稅額' JND_DESC
FROM TBL_SHIP A
    ,TBL_CUSTOMER B
WHERE A.CUM_NO=B.CUM_NO
  AND SMT_TAX<>0;

/*========================================================================================
		進貨單傳輸
=======================================================================================*/
/*進貨單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'B'+RCV_NO,RCV_DATE,CONVERT(VARCHAR,GETDATE(),111)+' 進貨單傳輸 '+RCV_NO+'('+B.SUP_NAME+')' JNL_DESC,1 JNL_BILL_TYPE,'WYS' JNL_CREATOR
FROM TBL_PO_RECV A
    ,TBL_SUPPLIER B
WHERE A.SUP_NO=B.SUP_NO;

/*傳票明細*/
/*5121=進貨*/
INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'B'+RCV_NO RCV_NO,1 JND_SEQNO,5121 ACT_NO,RCV_TOTAL ACT_AMOUNT
	,'傳輸-進貨' JND_DESC
FROM TBL_PO_RECV A
    ,TBL_SUPPLIER B
WHERE A.SUP_NO=B.SUP_NO;

/*傳票明細*/
/*1281=進項稅額*/
INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'B'+RCV_NO RCV_NO,2 JND_SEQNO,1281 ACT_NO,RCV_TAX ACT_AMOUNT
	,'傳輸-進項稅額' JND_DESC
FROM TBL_PO_RECV A
    ,TBL_SUPPLIER B
WHERE A.SUP_NO=B.SUP_NO
  AND A.RCV_TAX<>0;


/*傳票明細*/
/*2141=應付帳款*/
INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'B'+RCV_NO RCV_NO,3 JND_SEQNO,2141 ACT_NO,-(RCV_TOTAL+RCV_TAX) ACT_AMOUNT
	,'傳輸-應付帳款' JND_DESC
FROM TBL_PO_RECV A
    ,TBL_SUPPLIER B
WHERE A.SUP_NO=B.SUP_NO;


/*========================================================================================
		收款單傳輸
=======================================================================================*/
/* 收款單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'D'+M.ARR_NO JNL_NO,M.ARR_DATE JNL_DATE
      ,CONVERT(VARCHAR,GETDATE(),111)+' 收款單傳輸 '+'('+M.ARR_NO+'-'+B.CUM_NAME+CONVERT(VARCHAR,M.ARR_DATE,111)+')' JNL_DESC
      ,1 JNL_BILL_TYPE,'WYS' JNL_CREATOR
FROM TBL_AR_RECV M 
INNER JOIN TBL_CUSTOMER B ON M.CUM_NO=B.CUM_NO;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,1 JND_SEQNO,1111 ACT_NO,M.ARR_CASH,'傳輸-收取現金' JND_DESC
FROM TBL_AR_RECV M;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,2 JND_SEQNO,1131 ACT_NO,M.ARR_CHECK,'傳輸-收取票據' JND_DESC
FROM TBL_AR_RECV M;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,3 JND_SEQNO,2261 ACT_NO,M.ARR_FROM_ADVANCE,'傳輸-取用預收' JND_DESC
FROM TBL_AR_RECV M;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,4 JND_SEQNO,4191 ACT_NO,SUM(D.ARD_DISCOUNT) JND_AMOUNT,'傳輸-折讓總額' JND_DESC
FROM TBL_AR_RECV M 
INNER JOIN TBL_AR_RECV_DT D ON M.ARR_NO=D.ARR_NO
GROUP BY M.ARR_NO;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,5 JND_SEQNO,2261 ACT_NO,-M.ARR_TO_ADVANCE,'傳輸-累入預收' JND_DESC
FROM TBL_AR_RECV M;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,6 JND_SEQNO,1141 ACT_NO
			,-(SUM(D.ARD_DISCOUNT)+SUM(D.ARD_AMOUNT)) JND_AMOUNT,'傳輸-沖銷應收帳款' JND_DESC
FROM TBL_AR_RECV M 
INNER JOIN TBL_AR_RECV_DT D ON M.ARR_NO=D.ARR_NO
GROUP BY M.ARR_NO;


/*========================================================================================
	付款單傳輸--傳票主檔
=======================================================================================*/
/* 付款單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'E'+A.PAY_NO JNL_NO,A.PAY_DATE JNL_DATE
			,CONVERT(VARCHAR,GETDATE(),111)+' 付款單傳輸 '+'('+A.PAY_NO+'-'+B.SUP_NAME+CONVERT(VARCHAR,A.PAY_DATE,111)+')' JNL_DESC
			,1 JNL_BULL_TYPE,'WYS' JNL_CREATOR
FROM TBL_AP_PAY A
INNER JOIN TBL_SUPPLIER B ON A.SUP_NO=B.SUP_NO;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,1 JND_SEQNO,2141 ACT_NO,SUM(B.PAD_AMOUNT)+SUM(B.PAD_DISCOUNT) JND_AMOUNT,'傳輸-沖帳總額' JND_DESC
FROM TBL_AP_PAY A
INNER JOIN TBL_AP_PAY_DT B ON A.PAY_NO=B.PAY_NO
GROUP BY A.PAY_NO ;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,2 JND_SEQNO,1261 ACT_NO,A.PAY_TO_ADVANCE JND_AMOUNT,'傳輸-累入預付' JND_DESC
FROM TBL_AP_PAY A;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,3 JND_SEQNO,1111 ACT_NO,-A.PAY_CASH JND_AMOUNT,'傳輸-付出現金' JND_DESC
FROM TBL_AP_PAY A;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,4 JND_SEQNO,2131 ACT_NO,-A.PAY_CHECK JND_AMOUNT,'傳輸-付出票據' JND_DESC
FROM TBL_AP_PAY A;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,5 JND_SEQNO,1261 ACT_NO,-A.PAY_FROM_ADVANCE JND_AMOUNT,'傳輸-取用預付' JND_DESC
FROM TBL_AP_PAY A;

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,6 JND_SEQNO,5124 ACT_NO,-SUM(B.PAD_DISCOUNT) JND_AMOUNT,'傳輸-折讓總額' JND_DESC
FROM TBL_AP_PAY A
INNER JOIN TBL_AP_PAY_DT B ON A.PAY_NO=B.PAY_NO
GROUP BY A.PAY_NO ;





/*========================================================================================
資產負債表
=======================================================================================*/
SELECT D.TYP_MAJOR_TYPE,D.TYP_NO,D.TYP_NAME,SUBSTRING(C.ACT_NO,1,4) ACT_NO,C.ACT_NAME
			,SUM(B.JND_AMOUNT) AMOUNT
FROM TBL_ACNT_JOURNAL A
	INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
WHERE D.TYP_MAJOR_TYPE IN ('資產','負債','業主權益')
GROUP BY D.TYP_MAJOR_TYPE,D.TYP_NO,D.TYP_NAME,SUBSTRING(C.ACT_NO,1,4),C.ACT_NAME
UNION
SELECT '業主權益','99','保留盈餘(或累積虧損)','0000','盈餘'
			,SUM(B.JND_AMOUNT)  AMOUNT
FROM TBL_ACNT_JOURNAL A
	INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
WHERE D.TYP_MAJOR_TYPE NOT IN ('資產','負債','業主權益')
ORDER BY D.TYP_NO