DELETE TBL_ACNT_JOURNAL_DT;
DELETE TBL_ACNT_JOURNAL;

/* 付款單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'E'+A.PAY_NO JNL_NO,A.PAY_DATE JNL_DATE
			,CONVERT(VARCHAR,GETDATE(),111)+' 付款單傳輸 '+'('+B.SUP_NAME+CONVERT(VARCHAR,A.PAY_DATE,111)+')' JNL_DESC
			,1 JNL_BULL_TYPE,'WYS' JNL_CREATOR
FROM TBL_AP_PAY A
INNER JOIN TBL_SUPPLIER B ON A.SUP_NO=B.SUP_NO

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,1 JND_SEQNO,1111 ACT_NO,'C' JND_DC,A.PAY_CASH JND_AMOUNT,'傳輸-付出現金' JND_DESC
FROM TBL_AP_PAY A

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,2 JND_SEQNO,2131 ACT_NO,'C' JND_DC,A.PAY_CHECK JND_AMOUNT,'傳輸-付出票據' JND_DESC
FROM TBL_AP_PAY A

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,3 JND_SEQNO,1261 ACT_NO,'D' JND_DC,A.PAY_TO_ADVANCE JND_AMOUNT,'傳輸-累入預付' JND_DESC
FROM TBL_AP_PAY A

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,4 JND_SEQNO,1261 ACT_NO,'C' JND_DC,A.PAY_FROM_ADVANCE JND_AMOUNT,'傳輸-取用預付' JND_DESC
FROM TBL_AP_PAY A

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,5 JND_SEQNO,5124 ACT_NO,'C' JND_DC,SUM(B.PAD_DISCOUNT) JND_AMOUNT,'傳輸-折讓總額' JND_DESC
FROM TBL_AP_PAY A
INNER JOIN TBL_AP_PAY_DT B ON A.PAY_NO=B.PAY_NO
GROUP BY A.PAY_NO 

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'E'+A.PAY_NO,6 JND_SEQNO,1111 ACT_NO,'D' JND_DC,SUM(B.PAD_AMOUNT)+SUM(B.PAD_DISCOUNT) JND_AMOUNT,'傳輸-沖帳總額' JND_DESC
FROM TBL_AP_PAY A
INNER JOIN TBL_AP_PAY_DT B ON A.PAY_NO=B.PAY_NO
GROUP BY A.PAY_NO 