INSERT INTO TBL_ACNT_INIT (INI_YEAR,ACT_NO,INI_AMOUNT)
SELECT 2003 INI_YEAR,B.ACT_NO
			,SUM(B.JND_AMOUNT) AMOUNT
FROM TBL_ACNT_JOURNAL A
	INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
WHERE YEAR(A.JNL_DATE) <= 2003
	AND D.TYP_MAJOR_TYPE IN ('資產','負債','業主權益')
GROUP BY B.ACT_NO;
UPDATE TBL_SYS_PARAM SET SPR_ACNT_YEAR=2004
