SELECT
CONVERT (DATETIME,FLOOR(CONVERT(FLOAT,A.JNL_DATE))) JNL_DATE
,A.JNL_NO
,B.ACT_NO,B.JND_DESC
, DC = CASE 
		WHEN B.JND_AMOUNT >=0 THEN '­É'
		ELSE '¶U'
	END	
,	ACT_NAME = CASE 
		WHEN B.JND_AMOUNT >=0 THEN C.ACT_NAME
		ELSE '¡@¡@'+C.ACT_NAME
	END
, JND_AMOUNT = CASE 
		WHEN B.JND_AMOUNT >=0 THEN B.JND_AMOUNT
		ELSE B.JND_AMOUNT * -1
	END
FROM TBL_ACNT_JOURNAL A
INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
WHERE A.JNL_DATE >='01/01/2003'
	AND A.JNL_DATE <'01/01/2004'
ORDER BY A.JNL_DATE,A.JNL_NO,B.JND_SEQNO