SELECT A.PRD_NO
			,SUM(A.TRN_QTY) 期末數量
			,SUM(A.TRN_QTY*A.TRN_COST) 期末金額
			,CASE SUM(A.TRN_QTY)
				WHEN 0 THEN 0
				ELSE  SUM(A.TRN_QTY*A.TRN_COST)/SUM(A.TRN_QTY) 
				END 期末成本
FROM TBL_TRANSACTION A
WHERE A.TRN_DATETIME < '6/26/2006'
GROUP BY A.PRD_NO

