SELECT A.PRD_NO,A.QTY,A.AMOUNT
			,B.TRN_ONHAND,B.AMOUNT
FROM
(	SELECT A.PRD_NO
				,SUM(A.TRN_QTY) QTY
				,SUM(A.TRN_QTY*A.TRN_COST) AMOUNT
				,CASE SUM(A.TRN_QTY)
					WHEN 0 THEN 0
					ELSE  SUM(A.TRN_QTY*A.TRN_COST)/SUM(A.TRN_QTY) 
					END UC
	FROM TBL_TRANSACTION A
	WHERE A.TRN_DATETIME < '6/26/2006'
	GROUP BY A.PRD_NO
) A
,
(	SELECT A.TRN_DATETIME
				,A.PRD_NO
				,C.PRD_NAME
				,A.TRN_ONHAND
				,A.TRN_AVG_COST
				,A.TRN_ONHAND*A.TRN_AVG_COST AMOUNT
				,B.TRN_CNT
				,b.TimeCnt
	FROM 	TBL_TRANSACTION A 
	INNER JOIN TBL_PRODUCT C ON A.PRD_NO=C.PRD_NO
	INNER JOIN 	(	SELECT A.PRD_NO
											,TRN_CNT
											,MAX(TRN_ID) TRN_ID
											,count(*) timeCnt
								FROM TBL_TRANSACTION A
								INNER JOIN(	SELECT A.PRD_NO
																	,MAX(A.TRN_DATETIME) TRN_DATETIME
																	,COUNT(*) TRN_CNT
														FROM TBL_TRANSACTION A
														WHERE A.TRN_DATETIME <'6/26/2006'
														GROUP BY A.PRD_NO
													) B ON 	A.PRD_NO=B.PRD_NO
															AND A.TRN_DATETIME=B.TRN_DATETIME
								GROUP BY A.PRD_NO,b.trn_cnt
							) B ON A.TRN_ID=B.TRN_ID				
	WHERE A.TRN_ONHAND<>0
) B
WHERE A.PRD_NO=B.PRD_NO
	AND A.AMOUNT<>B.AMOUNT
