SELECT 2 GRP,A.TYP_MAJOR_TYPE,A.TYP_NO,TYP_NAME,A.ACT_NO,A.ACT_NAME,A.AMOUNT
			,A.AMOUNT/B.AMOUNT RATE
FROM
(	SELECT D.TYP_MAJOR_TYPE,D.TYP_NO,D.TYP_NAME,SUBSTRING(C.ACT_NO,1,4) ACT_NO,C.ACT_NAME
			,SUM(A.JND_AMOUNT) AMOUNT
	FROM
	(	SELECT B.JNL_NO,B.JND_SEQNO,B.ACT_NO,B.JND_AMOUNT
		FROM TBL_ACNT_JOURNAL A
			INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		WHERE A.JNL_DATE < '01/01/2004'
			AND A.JNL_DATE >= '01/01/2003'
		UNION
		SELECT 'INI',-1,ACT_NO,INI_AMOUNT
		FROM TBL_ACNT_INIT A
		WHERE A.INI_YEAR = YEAR('01/01/2003')
		UNION
		SELECT 'PROFIT',-1,'3353' ACT_NO
					,SUM(B.JND_AMOUNT)  AMOUNT
		FROM TBL_ACNT_JOURNAL A
			INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
			INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
			INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
		WHERE A.JNL_DATE < '01/01/2004'
			AND A.JNL_DATE >= '01/01/2003'
			AND D.TYP_MAJOR_TYPE NOT IN ('資產','負債','業主權益')
	) A
	INNER JOIN TBL_ACNT_ACCOUNT C ON A.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='業主權益'
	GROUP BY D.TYP_MAJOR_TYPE,D.TYP_NO,D.TYP_NAME,SUBSTRING(C.ACT_NO,1,4),C.ACT_NAME
) A
,
(	SELECT SUM(A.JND_AMOUNT) AMOUNT
	FROM
	(	SELECT B.JNL_NO,B.JND_SEQNO,B.ACT_NO,B.JND_AMOUNT
		FROM TBL_ACNT_JOURNAL A
			INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		WHERE A.JNL_DATE < '01/01/2004'
			AND A.JNL_DATE >= '01/01/2003'
		UNION
		SELECT 'INI',-1,ACT_NO,INI_AMOUNT
		FROM TBL_ACNT_INIT A
		WHERE A.INI_YEAR = YEAR('01/01/2003')
		UNION
		SELECT 'PROFIT',-1,'3353' ACT_NO
					,SUM(B.JND_AMOUNT)  AMOUNT
		FROM TBL_ACNT_JOURNAL A
			INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
			INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
			INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
			WHERE A.JNL_DATE < '01/01/2004'
				AND A.JNL_DATE >= '01/01/2003'
				AND D.TYP_MAJOR_TYPE NOT IN ('資產','負債','業主權益')
	) A
	INNER JOIN TBL_ACNT_ACCOUNT C ON A.ACT_NO=C.ACT_NO
	INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='業主權益'
) B