SELECT A.DELIVER_NO,A.EPY_NAME,A.SMT_DATE,A.TOTAL,B.RETURN_TOTAL
FROM
(	SELECT DELIVER_NO,EPY_NAME,SMT_DATE
	,SUM(TOTAL) TOTAL
	FROM
	(	SELECT A.SMT_DELIVER1 DELIVER_NO,C.EPY_NAME,CONVERT (DATETIME,FLOOR(CONVERT(FLOAT,A.SMT_DATE))) SMT_DATE,A.SMT_NO
		,B.SMD_QTY*B.SMD_UNIT_PRICE*0.5 TOTAL
		FROM TBL_SHIP a
		INNER JOIN TBL_SHIP_DT B ON A.SMT_NO=B.SMT_NO
		INNER JOIN TBL_EMPLOYE C ON A.SMT_DELIVER1=C.EPY_NO
		WHERE B.SMD_QTY >0
		
		UNION
		
		SELECT A.SMT_DELIVER2 DELIVER_NO,C.EPY_NAME,CONVERT (DATETIME,FLOOR(CONVERT(FLOAT,A.SMT_DATE))),A.SMT_NO
		,B.SMD_QTY*B.SMD_UNIT_PRICE*0.5 TOTAL
		FROM TBL_SHIP a
		INNER JOIN TBL_SHIP_DT B ON A.SMT_NO=B.SMT_NO
		INNER JOIN TBL_EMPLOYE C ON A.SMT_DELIVER2=C.EPY_NO
		WHERE B.SMD_QTY >0
	) A
	GROUP BY DELIVER_NO,EPY_NAME,SMT_DATE
) A
LEFT JOIN
(	SELECT DELIVER_NO,EPY_NAME,SMT_DATE
	,SUM(TOTAL) RETURN_TOTAL
	FROM
	(
		SELECT A.SMT_DELIVER1 DELIVER_NO,C.EPY_NAME,CONVERT (DATETIME,FLOOR(CONVERT(FLOAT,A.SMT_DATE))) SMT_DATE,A.SMT_NO
		,B.SMD_QTY*B.SMD_UNIT_PRICE*0.5 TOTAL
		FROM TBL_SHIP a
		INNER JOIN TBL_SHIP_DT B ON A.SMT_NO=B.SMT_NO
		INNER JOIN TBL_EMPLOYE C ON A.SMT_DELIVER1=C.EPY_NO
		WHERE B.SMD_QTY <0
	
	UNION
	
		SELECT A.SMT_DELIVER2 DELIVER_NO,C.EPY_NAME,CONVERT (DATETIME,FLOOR(CONVERT(FLOAT,A.SMT_DATE))),A.SMT_NO
		,B.SMD_QTY*B.SMD_UNIT_PRICE*0.5 TOTAL
		FROM TBL_SHIP a
		INNER JOIN TBL_SHIP_DT B ON A.SMT_NO=B.SMT_NO
		INNER JOIN TBL_EMPLOYE C ON A.SMT_DELIVER2=C.EPY_NO
		WHERE B.SMD_QTY <0
	) A
	GROUP BY DELIVER_NO,EPY_NAME,SMT_DATE
) B
ON A.DELIVER_NO=B.DELIVER_NO
AND A.SMT_DATE=B.SMT_DATE
ORDER BY A.DELIVER_NO,A.SMT_DATE 