SELECT SMT_NO,SMT_AMOUNT,SMT_NOT_CLEAN,RECEVED
,SMT_AMOUNT-RECEVED C_NOT_CLEAN
FROM
	(	SELECT S.SMT_NO,(S.SMT_TOTAL+S.SMT_TAX) SMT_AMOUNT,S.SMT_NOT_CLEAN
		,ISNULL(SUM(ARD_AMOUNT+ARD_DISCOUNT),0) RECEVED
		FROM  TBL_SHIP S LEFT JOIN TBL_AR_RECV_DT R ON S.SMT_NO=R.SMT_NO
		GROUP BY S.SMT_NO,S.SMT_TOTAL+S.SMT_TAX ,S.SMT_NOT_CLEAN
	) A
WHERE SMT_NOT_CLEAN<>(SMT_AMOUNT-RECEVED)