

DELETE TBL_ACNT_JOURNAL_DT
WHERE JNL_NO IN
(	SELECT JNL_NO
	FROM TBL_ACNT_JOURNAL_DT A
	GROUP BY A.JNL_NO
	HAVING SUM(A.JND_AMOUNT)<>0
);


DELETE TBL_ACNT_JOURNAL
WHERE JNL_NO IN
(	SELECT A.JNL_NO
	FROM TBL_ACNT_JOURNAL A
	LEFT JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	WHERE B.JNL_NO IS NULL
)
