DELETE TBL_ACNT_JOURNAL_DT;
DELETE TBL_ACNT_JOURNAL;

/* 收款單傳輸--傳票主檔*/
INSERT INTO TBL_ACNT_JOURNAL(JNL_NO,JNL_DATE,JNL_DESC,JNL_BILL_TYPE,JNL_CREATOR)
SELECT 'D'+M.ARR_NO JNL_NO,M.ARR_DATE JNL_DATE
      ,CONVERT(VARCHAR,GETDATE(),111)+' 收款單傳輸 '+'('+B.CUM_NAME+CONVERT(VARCHAR,M.ARR_DATE,111)+')' JNL_DESC,1 JNL_BILL_TYPE,'WYS' JNL_CREATOR
FROM TBL_AR_RECV M 
INNER JOIN TBL_CUSTOMER B ON M.CUM_NO=B.CUM_NO

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,1 JND_SEQNO,1111 ACT_NO,'D' JND_DC,M.ARR_CASH,'傳輸-收取現金' JND_DESC
FROM TBL_AR_RECV M 

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,2 JND_SEQNO,1131 ACT_NO,'D' JND_DC,M.ARR_CHECK,'傳輸-收取票據' JND_DESC
FROM TBL_AR_RECV M 

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,3 JND_SEQNO,2261 ACT_NO,'D' JND_DC,M.ARR_FROM_ADVANCE,'傳輸-取用預收' JND_DESC
FROM TBL_AR_RECV M

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,4 JND_SEQNO,4191 ACT_NO,'D' JND_DC,SUM(D.ARD_DISCOUNT) JND_AMOUNT,'傳輸-折讓總額' JND_DESC
FROM TBL_AR_RECV M 
INNER JOIN TBL_AR_RECV_DT D ON M.ARR_NO=D.ARR_NO
GROUP BY M.ARR_NO

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,5 JND_SEQNO,2261 ACT_NO,'C' JND_DC,M.ARR_FROM_ADVANCE,'傳輸-累入預收' JND_DESC
FROM TBL_AR_RECV M 

INSERT INTO TBL_ACNT_JOURNAL_DT (JNL_NO,JND_SEQNO,ACT_NO,JND_DC,JND_AMOUNT,JND_DESC)
SELECT 'D'+M.ARR_NO JNL_NO,6 JND_SEQNO,1141 ACT_NO,'C' JND_DC
			,SUM(D.ARD_DISCOUNT)+SUM(D.ARD_AMOUNT) JND_AMOUNT,'傳輸-沖銷應收帳款' JND_DESC
FROM TBL_AR_RECV M 
INNER JOIN TBL_AR_RECV_DT D ON M.ARR_NO=D.ARR_NO
GROUP BY M.ARR_NO
