UPDATE TBL_SHIP SET SMT_NOT_CLEAN=(S.SMT_TOTAL+S.SMT_TAX)-isnull(R.RECEIVED,0)
FROM TBL_SHIP S 
LEFT JOIN 
	(	SELECT SMT_NO,ISNULL(SUM(ARD_AMOUNT+ARD_DISCOUNT),0) RECEIVED
		FROM TBL_AR_RECV_DT
		GROUP BY SMT_NO
	) R ON S.SMT_NO=R.SMT_NO
