SELECT A.JNL_DATE,A.JNL_NO
			,B.JND_SEQNO,B.ACT_NO,C.ACT_NAME,B.JND_AMOUNT,B.JND_DESC
FROM TBL_ACNT_JOURNAL A
INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
WHERE A.JNL_DATE > CONVERT(DATETIME,'6/26/2006') 
	AND A.JNL_DATE < CONVERT(DATETIME,'7/26/2006')
ORDER BY A.JNL_DATE,A.JNL_NO