SELECT 1 SN,A.TYP_MAJOR_TYPE,A.ACT_NAME,A.ACT_NO,A.SubTotal
			,RATE=	CASE B.AMOUNT
							WHEN 	0 THEN 0
							ELSE (A.SubTotal/b.amount)*100 
							END
			,S.SPR_COR_NAME
FROM
(	SELECT D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
				,SUM(B.JND_AMOUNT) * -1 SubTotal
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業收入'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
) A,
(	SELECT D.TYP_MAJOR_TYPE
				,SUM(B.JND_AMOUNT) * -1 AMOUNT
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業收入'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE
) B
,TBL_SYS_PARAM S

union
SELECT 2 SN,A.TYP_MAJOR_TYPE,A.ACT_NAME,A.ACT_NO,A.SubTotal
			,RATE=	CASE B.AMOUNT
							WHEN 	0 THEN 0
							ELSE (A.SubTotal/b.amount)*100 
							END
			,S.SPR_COR_NAME
FROM
(	SELECT D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
				,SUM(B.JND_AMOUNT) SubTotal
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業成本'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
) A,
(	SELECT D.TYP_MAJOR_TYPE
				,SUM(B.JND_AMOUNT) AMOUNT
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業成本'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE
) B
,TBL_SYS_PARAM S

UNION
SELECT 3 SN,A.TYP_MAJOR_TYPE,A.ACT_NAME,A.ACT_NO,A.SubTotal
			,RATE=	CASE B.AMOUNT
							WHEN 	0 THEN 0
							ELSE (A.SubTotal/b.amount)*100 
							END
			,S.SPR_COR_NAME
FROM
(	SELECT D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
				,SUM(B.JND_AMOUNT) SubTotal
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業費用'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
) A,
(	SELECT D.TYP_MAJOR_TYPE
				,SUM(B.JND_AMOUNT) AMOUNT
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業費用'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE
) B
,TBL_SYS_PARAM S

UNION
SELECT 4 SN,A.TYP_MAJOR_TYPE,A.ACT_NAME,A.ACT_NO,A.SubTotal
			,RATE=	CASE B.AMOUNT
							WHEN 	0 THEN 0
							ELSE (A.SubTotal/b.amount)*100 
							END
			,S.SPR_COR_NAME
FROM
(	SELECT D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
				,SUM(B.JND_AMOUNT) * -1 SubTotal
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業外收入及費用'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
) A,
(	SELECT D.TYP_MAJOR_TYPE
				,SUM(B.JND_AMOUNT) * -1 AMOUNT
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='營業外收入及費用'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE
) B
,TBL_SYS_PARAM S

UNION
SELECT 5 SN,A.TYP_MAJOR_TYPE,A.ACT_NAME,A.ACT_NO,A.SubTotal
			,RATE=	CASE B.AMOUNT
							WHEN 	0 THEN 0
							ELSE (A.SubTotal/b.amount)*100 
							END
			,S.SPR_COR_NAME
FROM
(	SELECT D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
				,SUM(B.JND_AMOUNT) SubTotal
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='所得稅費用(或利益)'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE,C.ACT_NAME,C.ACT_NO
) A,
(	SELECT D.TYP_MAJOR_TYPE
				,SUM(B.JND_AMOUNT) AMOUNT
	FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
		INNER JOIN TBL_ACNT_TYPE D ON C.TYP_NO=D.TYP_NO
	WHERE D.TYP_MAJOR_TYPE ='所得稅費用(或利益)'
		and year(A.JNL_DATE)=2003
	GROUP BY  D.TYP_MAJOR_TYPE
) B
,TBL_SYS_PARAM S

ORDER BY SN,ACT_NO