--=========================================================
--	DateFrom='04/01/2003'
--	DateTo	='06/01/2003'
--=========================================================
SELECT A.JNL_DATE,A.JNL_NO,A.JND_SEQNO,JND_DESC,A.ACT_NO,ACT_NAME,AMOUNT
			,'DEBIT'= CASE  
								WHEN AMOUNT>=0 THEN AMOUNT
								ELSE 0
							END
			,'CREDIT'= CASE  
								WHEN AMOUNT<0 THEN -AMOUNT
								ELSE 0
							END

FROM
(	SELECT A.JNL_DATE,A.JNL_NO,B.JND_SEQNO,B.ACT_NO,B.JND_DESC,B.JND_AMOUNT AMOUNT
	FROM TBL_ACNT_JOURNAL A
	INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
	WHERE A.JNL_DATE >= '04/01/2003'
		AND A.JNL_DATE < '06/01/2003'
	UNION
	SELECT '04/01/2003'JNL_DATE
				,'@@INIT' JNL_NO
				,0 JND_SEQNO
				,ACT_NO
				,'´Áªìª÷ÃB' JND_DESC
				,SUM(AMOUNT) AMOUNT
	FROM
	(	SELECT B.ACT_NO,B.JND_AMOUNT AMOUNT
		FROM TBL_ACNT_JOURNAL A
		INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
		WHERE A.JNL_DATE >= '01/01/'+CAST(YEAR('04/01/2003') AS VARCHAR)
			AND A.JNL_DATE < '04/01/2003'
		UNION
		SELECT A.ACT_NO,INI_AMOUNT AMOUNT
		FROM TBL_ACNT_INIT A
		WHERE A.INI_YEAR=YEAR('04/01/2003')
	) A
	GROUP BY A.ACT_NO
) A INNER JOIN TBL_ACNT_ACCOUNT B ON A.ACT_NO=B.ACT_NO
WHERE A.ACT_NO BETWEEN '00000' AND '99999'
ORDER BY A.ACT_NO,JNL_DATE,JNL_NO,JND_SEQNO

