--=========================================================
--	DateTo	='12/31/2003'
--=========================================================
SELECT B.ACT_NO,C.ACT_NAME,SUM(B.JND_AMOUNT) DEBIT,0 CREDIT,SUM(B.JND_AMOUNT) AMOUNT
FROM TBL_ACNT_JOURNAL A 
INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
WHERE A.JNL_DATE < '12/31/2003'
GROUP BY B.ACT_NO,C.ACT_NAME
HAVING SUM(B.JND_AMOUNT)>=0

UNION
SELECT B.ACT_NO,C.ACT_NAME,0 DEBIT,-SUM(B.JND_AMOUNT) CREDIT,SUM(B.JND_AMOUNT) AMOUNT
FROM TBL_ACNT_JOURNAL A 
INNER JOIN TBL_ACNT_JOURNAL_DT B ON A.JNL_NO=B.JNL_NO
INNER JOIN TBL_ACNT_ACCOUNT C ON B.ACT_NO=C.ACT_NO
WHERE A.JNL_DATE < '12/31/2003'
GROUP BY B.ACT_NO,C.ACT_NAME
HAVING SUM(B.JND_AMOUNT)<0
