SELECT A.RCV_NO,A.RCV_DATE,A.SUP_NO
			,B.RCD_SEQNO,B.PRD_NO,B.RCD_QTY,B.RCD_UNIT_PRICE
FROM TBL_PO_RECV A
INNER JOIN TBL_PO_RECV_DT B ON A.RCV_NO=B.RCV_NO
WHERE A.RCV_DATE > CONVERT(DATETIME ,'6/26/2006') 
	AND A.RCV_DATE < CONVERT(DATETIME,'7/26/2006')
	AND B.RCD_QTY<0
ORDER BY A.RCV_DATE,A.RCV_NO,B.RCD_SEQNO