SELECT A.CUM_NO
	,B.CUM_NAME
	,S.SPR_COR_NAME,SPR_TEL,SPR_FAX,SPR_ADDR     
	,ISNULL(SUM(A.SMT_TOTAL),0) TOTAL_AR
	,ISNULL(SUM(C.ARD_AMOUNT),0) TOTAL_RECEIVED
	,ISNULL(SUM(A.SMT_NOT_CLEAN),0) TOTAL_NOT_CLEAN
	,ISNULL(SUM(C.ARD_DISCOUNT),0) TOTAL_DISCOUNT
	,CASE (ISNULL(SUM(C.ARD_AMOUNT),0)+ISNULL(SUM(C.ARD_DISCOUNT),0))
		WHEN 0 THEN 0
		ELSE
			ISNULL(SUM(C.ARD_DISCOUNT),0)/(ISNULL(SUM(C.ARD_AMOUNT),0)+ISNULL(SUM(C.ARD_DISCOUNT),0)) 
		END Discount_Ratio
FROM TBL_SHIP A
INNER JOIN TBL_CUSTOMER B ON A.CUM_NO=B.CUM_NO
LEFT JOIN (	SELECT C.SMT_NO
									,ISNULL(SUM(C.ARD_AMOUNT),0) ARD_AMOUNT
									,ISNULL(SUM(C.ARD_DISCOUNT),0) ARD_DISCOUNT			
						FROM TBL_AR_RECV_DT C 
						GROUP BY C.SMT_NO	
					)	C ON A.SMT_NO=C.SMT_NO
,TBL_SYS_PARAM S
WHERE A.SMT_STATUS>0
GROUP BY A.CUM_NO
	,B.CUM_NAME
	,S.SPR_COR_NAME,SPR_TEL,SPR_FAX,SPR_ADDR    
ORDER BY SUM(C.ARD_DISCOUNT) DESC