SELECT C_TRN_TYPE,PRD_NO,TRN_ID,TRN_SRC_NO,TRN_DATETIME,TRN_QTY,TRN_ONHAND,TRN_COST,TRN_AVG_COST
FROM
(
SELECT  CASE T.TRN_TYPE
        WHEN 0 THEN '期初'
        WHEN 1 THEN '進貨'
        WHEN 2 THEN '銷貨'
        WHEN 3 THEN '調整'
        ELSE        '不明'
        END C_TRN_TYPE
,P.PRD_NAME+ '  ('+P.PRD_NO+')' C_PRD_NAME
,T.*,S.*
FROM TBL_TRANSACTION T INNER JOIN TBL_PRODUCT P ON T.PRD_NO=P.PRD_NO
,TBL_SYS_PARAM S
)T
WHERE T.PRD_NO = 'R9G954-A01-1-050-02'
--	and t.trn_src_no like '2004080%'
ORDER BY T.PRD_NO,T.TRN_DATETIME